# Day 14: Restroom Redoubt

https://adventofcode.com/2024/day/14

## --- Part One ---

In [121]:
# Predict the motion of the robots in your list within a space which is 101 tiles wide and 103 tiles tall.
# in this sample, the robots are in a space which is only 11 tiles wide and 7 tiles tall.
import numpy as np
from pprint import pprint
import re
import math

file = 'input.txt'
file = 'sample.txt'

# init vars
robots = []
vectors = []
steps = 10

room = np.array([])

# room sizes vary based on input/sample
if file == 'input.txt':
    room = np.zeros((103,101),dtype=int)
else:
    room = np.zeros((7,11),dtype=int)

print('room size:', np.size(room,0),'x',np.size(room,1))

# open file & load content
with open(file, 'r') as f:
    lines = f.read().split('\n')
    for line in lines:
        data = re.match(r"p=(\d+),(\d+) v=([-]?\d+),([-]?\d+)",line)

        # extract robot pos | positions swapped
        robot_pos = [int(data.group(2)),int(data.group(1))]

        # robot vector | positions swapped
        robot_vector = [int(data.group(4)),int(data.group(3))]

        # append to overall lists
        robots.append(robot_pos)
        vectors.append(robot_vector)



# 
for idx in range(0,len(robots)):
    pos = np.array(robots[idx])
    vec = np.array(vectors[idx])
    # print(pos,vec)
    # print('--')
    for step in range(1,steps+1):
        pos = pos+vec
        if pos[0] < 0:
            pos[0] = np.size(room,0)+pos[0]
        elif pos[0] >= np.size(room,0):
            pos[0] = pos[0]-np.size(room,0)
        if pos[1] < 0:
            pos[1] = np.size(room,1)+pos[1]
        elif pos[1] >= np.size(room,1):
            pos[1] = pos[1]-np.size(room,1)
        # print('pos after', step, 'step(s):',pos)
    # print('==')
    # set the final position of the robot in the room
    room[pos[0],pos[1]] +=1

print(room)


# split the room into quadrants
row_slice_len = math.floor(np.size(room,0)/2)
col_slice_len = math.floor(np.size(room,1)/2)

q1 = room[0:row_slice_len, 0:col_slice_len]
q2 = room[0:row_slice_len, -col_slice_len:]
q3 = room[-row_slice_len:, 0:col_slice_len]
q4 = room[-row_slice_len:, -col_slice_len:]
safety_factor = np.sum(q1)*np.sum(q2)*np.sum(q3)*np.sum(q4)

print('\nAnswer to part 1:', safety_factor)

room size: 7 x 11
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 0 0 0]
 [2 0 0 0 0 0 0 0 2 0 1]
 [0 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]

Answer to part 1: 24


## --- Part Two ---

In [158]:
# Predict the motion of the robots in your list within a space which is 101 tiles wide and 103 tiles tall.
# in this sample, the robots are in a space which is only 11 tiles wide and 7 tiles tall.
import numpy as np
from pprint import pprint
import re
import math
from copy import deepcopy
import sys
from PIL import Image

file = 'input.txt'
# file = 'sample.txt'

# init vars
robots = []
vectors = []
# from earlier submission i knew it was between 1-10000
steps = 10000

room = np.array([])

# room sizes vary based on input/sample
if file == 'input.txt':
    room = np.zeros((103,101),dtype=int)
else:
    room = np.zeros((7,11),dtype=int)

# open file & load content
with open(file, 'r') as f:
    lines = f.read().split('\n')
    for line in lines:
        data = re.match(r"p=(\d+),(\d+) v=([-]?\d+),([-]?\d+)",line)

        # extract robot pos | positions swapped
        robot_pos = [int(data.group(2)),int(data.group(1))]

        # robot vector | positions swapped
        robot_vector = [int(data.group(4)),int(data.group(3))]

        # append to overall lists
        robots.append(robot_pos)
        vectors.append(robot_vector)

for step in range(1,steps+1):
    # print('=== Step',step,'===')
    for idx in range(0, len(robots)):
        pos = np.array(robots[idx])
        vec = np.array(vectors[idx])
        new_pos = pos+vec
        if new_pos[0] < 0:
            new_pos[0] = np.size(room,0)+new_pos[0]
        elif new_pos[0] >= np.size(room,0):
            new_pos[0] = new_pos[0]-np.size(room,0)
        if new_pos[1] < 0:
            new_pos[1] = np.size(room,1)+new_pos[1]
        elif new_pos[1] >= np.size(room,1):
            new_pos[1] = new_pos[1]-np.size(room,1)
        robots[idx] = new_pos
    # print('pos after', step, 'step(s):',robots)
    # print('===')

    new_room = np.zeros_like(room, dtype=np.uint8)
    for x in robots:
       new_room[x[0],x[1]] = 255

    # print(new_room)
    image = Image.fromarray(new_room)

    image_name = 'imgs/step'+str(step)+'.png'

    # Save the image
    # image.save(image_name)

print('\nAnswer to part 2:', 'manual search')


Answer to part 2: manual search
